apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-ram-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app:  cpu-ram-api
  template:
    metadata:
      labels:
        app: cpu-ram-api
    spec:
      containers:
      - name: myapp
        image: vplauzon/cpu-ram-request-api:1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "6M"
            cpu: "250m"
          limits:
            memory: "64M"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: cpu-ram-api
  