apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiple-file-to-output-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multiple-file-to-output-pod
  template:
    metadata:
      labels:
        app: multiple-file-to-output-pod
    spec:
      containers:
      - name: main-container
        image: busybox
        args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$i: $(date) dog" >> /var/log/mylogs/1.log;
            echo "$i: $(date) cat" >> /var/log/mylogs/2.log;
            i=$((i+1));
            sleep 1;
          done
        volumeMounts:
        - name: logs
          mountPath: /var/log/mylogs
      - name:  log-display
        image: busybox
        args: [/bin/sh, -c, 'tail -n+1 -f /var/log/mylogs/*.log']
        volumeMounts:
        - name: logs
          mountPath: /var/log/mylogs
      volumes:
      - name: logs
        emptyDir: {}
