apiVersion: v1
kind: Pod
metadata:
  name: test-log-emit
spec:
  containers:
  - name: count
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date)" >> /var/log/1.log;
        echo "$(date) INFO $i" >> /var/log/2.log;
        i=$((i+1));
        sleep 1;
      done
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    hostPath:
      # directory location on host
      path: /var/log
      # this field is optional
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: test-log-output
spec:
  containers:
  - name:  log-display
    image: busybox
    args: [/bin/sh, -c, 'tail -n+1 -f /var/log/1.log']
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  volumes:
  - name: varlog
    hostPath:
      # directory location on host
      path: /var/log
      # this field is optional
      type: DirectoryOrCreate
