apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels:
    app: demo-app
spec:
  replicas: 19
  selector:
    matchLabels:
      app: demo-app
  template:
      metadata:
        labels:
          app: demo-app
      spec:
        containers:
        - name: myapi
          image: vplauzon/get-started:part2-no-redis
          resources:
            requests:
              memory: "1.5G"
              cpu: "250m"
            limits:
              memory: "2G"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          ports:
          - containerPort: 80