apiVersion: v1
kind: Pod
metadata:
  name: test-id-pod
  labels:
    app: little-pod
    aadpodidbinding:  little-pod-binding
spec:
  containers:
  - name: main-container
    image: appropriate/curl
    args:
    - /bin/sh
    - -c
    - >
      while true;
      do
        sleep 1;
      done
