apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk-stateful-set
  labels:
    app: busy-box-with-stateful-set-disk
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stateful-disk-pod
  serviceName:  stateful-disk-set
  template:
    metadata:
      labels:
        app: stateful-disk-pod
    spec:
      containers:
      - name:  busy
        image: vplauzon/get-started:part2-no-redis
        ports:
        - containerPort: 80
        volumeMounts:
        - name: azure-managed-disk-set
          mountPath: /buffer
  volumeClaimTemplates:
  - metadata:
      name: azure-managed-disk-set
    spec:
      storageClassName: managed-premium
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
